CREATE TABLE "users" (
                         "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "NAME" VARCHAR(255) NOT NULL,
                         "LOGIN" VARCHAR(255) NOT NULL,
                         "PASSWORD" VARCHAR(255) NOT NULL
);